* [[http://www.thenation.com/article/181555/survival-sexiest?page=0%2C2][evolutionary psychology]] - <2014-09-18 Thu>
* [[http://slatestarcodex.com/2014/09/30/i-can-tolerate-anything-except-the-outgroup/][tolerating the intolerant]] <2014-10-10 Fri>
* [[http://slatestarcodex.com/2014/10/10/open-thread-6-open-renewal/][AI crankitude]] <2014-10-10 Fri>
* the islams <2014-10-15 Wed>

  You Can't Get There From Here

  A recent [[http://www.realclearpolitics.com/video/2014/10/03/bill_maher_vs_ben_affleck_on_islam_mafia_that_will_fucking_kill_you_if_you_say_the_wrong_thing.html][video]] has been making the rounds of the internet. In an episode of something called /Real Time/ (presumably meant to be distinguished from /Lunch Time/), Ben Affleck, Bill Maher, and Sam Harris really got into it over the questions of whether one should condemn all Muslims in general and Islam in particular over the actions of extremists, with Affleck making the argument against stereotyping while Harris and Maher quoted some statistics about what the majority of Muslims believe. It was about as unproductive a discussion as you can imagine.

  It's not my intention here to referee between the disputants, for one simple reason: the problem with the entire debate is a framing that ascribes an essential nature to religious ideas that the ideas themselves do not possess. 

  Looking back on the historical record, you can find about as many different ways of practicing Islam, Christianity, or any other religion as there were societies that adopted those faiths. If retrograde thinking, or an implacable aversion to modernity, was some essential or fixed lodestar of Islamic thought (in, implicitly, opposition to "progressive" Christianity), you wouldn't expect to find a period of relative peace, tolerance, and innovation in the medieval Islamic world, at a time when Christian polities generally experienced periods of stagnation. If you were a Jew circa the 11th century C.E., it would be a no-brainer to decide which society you wanted to live in, that of the Baghdad-based Abbasids, or that of the Holy Roman Empire. But of course the historical record is fairly clear: those Islamic empires did exist, were about as tolerant, religiously speaking, as you could expect to get, and furthermore were generally farther along in most areas of what we take to constitute societal development than Western Christianity.

  Usually it's at this point that people who are hell-bent on making bad essentialist arguments about Islam say something like, "yes, well, the Golden Age was great, but they haven't done anything since." Putting aside the obvious fact that condensing some eight centuries of post-Abbasid Islamic history 
